"""Migrate the local Study Buddy SQLite database to Supabase Postgres.

Required environment variable:
    DATABASE_URL=postgresql://...

Optional:
    SQLITE_DB_PATH=studybuddy.db
"""

import os
import re
import sqlite3
from pathlib import Path

import psycopg
from dotenv import load_dotenv

load_dotenv()

SQLITE_DB_PATH = Path(os.getenv("SQLITE_DB_PATH", "studybuddy.db"))
DATABASE_URL = os.getenv("DATABASE_URL")

BOOLEAN_COLUMNS = {"activo", "leido"}
SKIP_TABLES = {"sqlite_sequence"}


def quote_identifier(name):
    return '"' + name.replace('"', '""') + '"'


def map_column_type(sqlite_type, column_name):
    normalized = (sqlite_type or "TEXT").upper()
    if column_name in BOOLEAN_COLUMNS or "BOOLEAN" in normalized:
        return "BOOLEAN"
    if "INT" in normalized:
        return "INTEGER"
    if "DECIMAL" in normalized or "NUMERIC" in normalized or "REAL" in normalized or "FLOAT" in normalized or "DOUBLE" in normalized:
        return "NUMERIC"
    if "DATE" == normalized:
        return "DATE"
    if "TIME" == normalized:
        return "TIME"
    if "TIMESTAMP" in normalized or "DATETIME" in normalized:
        return "TIMESTAMP"
    return "TEXT"


def normalize_default(default_value, postgres_type):
    if default_value is None:
        return ""
    value = str(default_value).strip()
    if value.upper() == "CURRENT_TIMESTAMP":
        return " DEFAULT CURRENT_TIMESTAMP"
    if postgres_type == "BOOLEAN":
        if value in {"1", "'1'"}:
            return " DEFAULT TRUE"
        if value in {"0", "'0'"}:
            return " DEFAULT FALSE"
    return f" DEFAULT {value}"


def get_sqlite_tables(sqlite_conn):
    rows = sqlite_conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
        ORDER BY name
        """
    ).fetchall()
    return [row[0] for row in rows if row[0] not in SKIP_TABLES]


def create_table_sql(sqlite_conn, table_name):
    columns = sqlite_conn.execute(f"PRAGMA table_info({quote_identifier(table_name)})").fetchall()
    definitions = []
    for column in columns:
        _, name, sqlite_type, not_null, default_value, primary_key = column
        if primary_key:
            definitions.append(f"{quote_identifier(name)} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            continue
        postgres_type = map_column_type(sqlite_type, name)
        definition = f"{quote_identifier(name)} {postgres_type}"
        if not_null:
            definition += " NOT NULL"
        definition += normalize_default(default_value, postgres_type)
        definitions.append(definition)
    return f"CREATE TABLE IF NOT EXISTS {quote_identifier(table_name)} (\n    " + ",\n    ".join(definitions) + "\n);"


def convert_value(value, column_name):
    if column_name in BOOLEAN_COLUMNS and value is not None:
        return bool(value)
    return value


def copy_table(sqlite_conn, postgres_conn, table_name):
    rows = sqlite_conn.execute(f"SELECT * FROM {quote_identifier(table_name)}").fetchall()
    if not rows:
        return 0

    columns = [description[0] for description in sqlite_conn.execute(f"SELECT * FROM {quote_identifier(table_name)} LIMIT 1").description]
    column_list = ", ".join(quote_identifier(column) for column in columns)
    placeholders = ", ".join(["%s"] * len(columns))
    insert_sql = f"INSERT INTO {quote_identifier(table_name)} ({column_list}) VALUES ({placeholders})"

    with postgres_conn.cursor() as cursor:
        for row in rows:
            values = [convert_value(row[column], column) for column in columns]
            cursor.execute(insert_sql, values)
    return len(rows)


def reset_identity_sequence(postgres_conn, table_name):
    with postgres_conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT pg_get_serial_sequence(%s, 'id')
            """,
            (table_name,),
        )
        result = cursor.fetchone()
        sequence_name = result[0] if result else None
        if not sequence_name:
            return
        cursor.execute(f"SELECT COALESCE(MAX(id), 1) FROM {quote_identifier(table_name)}")
        max_id = cursor.fetchone()[0]
        cursor.execute("SELECT setval(%s, %s, true)", (sequence_name, max_id))


def create_indexes(postgres_conn):
    index_statements = [
        "CREATE INDEX IF NOT EXISTS idx_estudiante_email ON estudiantes(email)",
        "CREATE INDEX IF NOT EXISTS idx_profesor_email ON profesores(email)",
        "CREATE INDEX IF NOT EXISTS idx_clases_fecha ON clases(fecha)",
        "CREATE INDEX IF NOT EXISTS idx_clases_estudiante ON clases(estudiante_id)",
        "CREATE INDEX IF NOT EXISTS idx_pizarra_paginas_estudiante ON pizarra_paginas(estudiante_id)",
        "CREATE INDEX IF NOT EXISTS idx_pizarra_paginas_folder ON pizarra_paginas(estudiante_id, folder_id)",
        "CREATE INDEX IF NOT EXISTS idx_student_files_folder ON student_files(estudiante_id, folder_id)",
        "CREATE INDEX IF NOT EXISTS idx_student_folders_estudiante ON student_folders(estudiante_id, name)",
    ]
    with postgres_conn.cursor() as cursor:
        for statement in index_statements:
            try:
                cursor.execute(statement)
            except Exception as error:
                print(f"Skipping index: {statement} ({error})")
                postgres_conn.rollback()


def main():
    if not DATABASE_URL:
        raise SystemExit("DATABASE_URL is required")
    if not SQLITE_DB_PATH.exists():
        raise SystemExit(f"SQLite database not found: {SQLITE_DB_PATH}")

    sqlite_conn = sqlite3.connect(SQLITE_DB_PATH)
    sqlite_conn.row_factory = sqlite3.Row
    postgres_conn = psycopg.connect(DATABASE_URL)

    try:
        tables = get_sqlite_tables(sqlite_conn)
        with postgres_conn.cursor() as cursor:
            for table_name in tables:
                sql = create_table_sql(sqlite_conn, table_name)
                cursor.execute(sql)
        postgres_conn.commit()

        for table_name in tables:
            count = copy_table(sqlite_conn, postgres_conn, table_name)
            postgres_conn.commit()
            reset_identity_sequence(postgres_conn, table_name)
            postgres_conn.commit()
            print(f"Migrated {count} rows from {table_name}")

        create_indexes(postgres_conn)
        postgres_conn.commit()
        print("Migration complete.")
    finally:
        sqlite_conn.close()
        postgres_conn.close()


if __name__ == "__main__":
    main()
