-- Study Buddy Supabase/Postgres schema

CREATE TABLE IF NOT EXISTS estudiantes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    edad INTEGER,
    fecha_nacimiento DATE,
    nivel_educativo VARCHAR(50),
    foto_perfil VARCHAR(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS profesores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    especialidad VARCHAR(100),
    foto_perfil VARCHAR(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS materias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    nivel VARCHAR(50),
    creditos INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS syllabus (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_id INTEGER NOT NULL REFERENCES materias(id),
    profesor_id INTEGER NOT NULL REFERENCES profesores(id),
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    objetivos TEXT,
    contenido TEXT,
    metodologia TEXT,
    evaluacion TEXT,
    bibliografia TEXT,
    "año_academico" VARCHAR(20),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_id INTEGER NOT NULL REFERENCES materias(id),
    profesor_id INTEGER NOT NULL REFERENCES profesores(id),
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    duracion_horas NUMERIC(4,2),
    modalidad VARCHAR(20) NOT NULL,
    direccion VARCHAR(255),
    link_virtual VARCHAR(255),
    estado VARCHAR(20) DEFAULT 'programada',
    notas_clase TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS asistencia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clase_id INTEGER NOT NULL REFERENCES clases(id),
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    estado VARCHAR(20) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    materia_id INTEGER NOT NULL REFERENCES materias(id),
    tipo_evaluacion VARCHAR(50) NOT NULL,
    titulo VARCHAR(200),
    calificacion NUMERIC(5,2) NOT NULL,
    calificacion_maxima NUMERIC(5,2) DEFAULT 100,
    porcentaje NUMERIC(5,2),
    fecha_evaluacion DATE NOT NULL,
    trimestre VARCHAR(20),
    comentarios TEXT,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS horas_estudiante (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    materia_id INTEGER NOT NULL REFERENCES materias(id),
    total_horas NUMERIC(6,2) DEFAULT 0,
    mes VARCHAR(7),
    "año" INTEGER,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reportes_clase (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clase_id INTEGER NOT NULL REFERENCES clases(id),
    profesor_id INTEGER NOT NULL REFERENCES profesores(id),
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    tema_cubierto TEXT NOT NULL,
    objetivos_cumplidos TEXT,
    "desempeño_estudiante" TEXT,
    areas_mejora TEXT,
    tareas_asignadas TEXT,
    observaciones TEXT,
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metacognicion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    clase_id INTEGER REFERENCES clases(id),
    fecha DATE NOT NULL,
    comprension_tema INTEGER CHECK(comprension_tema BETWEEN 1 AND 5),
    dificultad_percibida INTEGER CHECK(dificultad_percibida BETWEEN 1 AND 5),
    confianza_nivel INTEGER CHECK(confianza_nivel BETWEEN 1 AND 5),
    que_aprendi TEXT,
    que_fue_dificil TEXT,
    que_estrategias_use TEXT,
    como_mejorar TEXT,
    estado_animo VARCHAR(50),
    nivel_estres INTEGER CHECK(nivel_estres BETWEEN 1 AND 5),
    tiempo_estudio_horas NUMERIC(4,2),
    esfuerzo_percibido INTEGER CHECK(esfuerzo_percibido BETWEEN 1 AND 5),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metricas_objetivas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    fecha DATE NOT NULL,
    autonomia_porcentaje NUMERIC(5,2),
    solicitudes_ayuda INTEGER DEFAULT 0,
    tiempo_sin_ayuda_minutos INTEGER DEFAULT 0,
    fluidez_porcentaje NUMERIC(5,2),
    velocidad_respuesta_segundos NUMERIC(6,2),
    precision_porcentaje NUMERIC(5,2),
    resiliencia_porcentaje NUMERIC(5,2),
    intentos_antes_exito INTEGER DEFAULT 0,
    persistencia_score NUMERIC(5,2),
    racha_dias_consecutivos INTEGER DEFAULT 0,
    ultima_actividad DATE,
    nivel_dominio VARCHAR(50),
    progreso_semanal NUMERIC(5,2),
    promedio_general NUMERIC(5,2),
    tiempo_sesion_minutos INTEGER,
    sesiones_completadas INTEGER DEFAULT 0,
    ejercicios_completados INTEGER DEFAULT 0,
    fecha_calculo TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS estilo_cognitivo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    tipo_estilo VARCHAR(50) NOT NULL,
    nivel_intensidad INTEGER CHECK(nivel_intensidad BETWEEN 1 AND 5),
    observaciones TEXT,
    fecha_evaluacion DATE NOT NULL,
    evaluado_por INTEGER REFERENCES profesores(id),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS objetivos_aprendizaje (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id),
    materia_id INTEGER NOT NULL REFERENCES materias(id),
    objetivo TEXT NOT NULL,
    descripcion TEXT,
    fecha_inicio DATE NOT NULL,
    fecha_objetivo DATE,
    estado VARCHAR(20) DEFAULT 'en_progreso',
    progreso_porcentaje NUMERIC(5,2) DEFAULT 0,
    fecha_completado DATE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mensajes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_tipo VARCHAR(20) NOT NULL,
    remitente_id INTEGER NOT NULL,
    destinatario_tipo VARCHAR(20) NOT NULL,
    destinatario_id INTEGER NOT NULL,
    asunto VARCHAR(200),
    mensaje TEXT NOT NULL,
    leido BOOLEAN DEFAULT FALSE,
    fecha_lectura TIMESTAMP,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_folders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(estudiante_id, name)
);

CREATE TABLE IF NOT EXISTS pizarra_paginas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id) ON DELETE CASCADE,
    folder_id INTEGER REFERENCES student_folders(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,
    pagina_data TEXT NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES estudiantes(id) ON DELETE CASCADE,
    folder_id INTEGER REFERENCES student_folders(id) ON DELETE SET NULL,
    filename TEXT NOT NULL,
    filepath TEXT NOT NULL,
    category TEXT DEFAULT 'casillero',
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_estudiante_email ON estudiantes(email);
CREATE INDEX IF NOT EXISTS idx_profesor_email ON profesores(email);
CREATE INDEX IF NOT EXISTS idx_clases_fecha ON clases(fecha);
CREATE INDEX IF NOT EXISTS idx_clases_estudiante ON clases(estudiante_id);
CREATE INDEX IF NOT EXISTS idx_notas_estudiante ON notas(estudiante_id);
CREATE INDEX IF NOT EXISTS idx_metricas_estudiante_fecha ON metricas_objetivas(estudiante_id, fecha);
CREATE INDEX IF NOT EXISTS idx_metacognicion_estudiante ON metacognicion(estudiante_id);
CREATE INDEX IF NOT EXISTS idx_reportes_estudiante ON reportes_clase(estudiante_id);
CREATE INDEX IF NOT EXISTS idx_pizarra_paginas_estudiante ON pizarra_paginas(estudiante_id);
CREATE INDEX IF NOT EXISTS idx_pizarra_paginas_folder ON pizarra_paginas(estudiante_id, folder_id);
CREATE INDEX IF NOT EXISTS idx_student_folders_estudiante ON student_folders(estudiante_id, name);
CREATE INDEX IF NOT EXISTS idx_student_files_folder ON student_files(estudiante_id, folder_id);

CREATE OR REPLACE VIEW vista_resumen_estudiante AS
SELECT
    e.id,
    e.nombre || ' ' || e.apellido AS nombre_completo,
    e.edad,
    e.nivel_educativo,
    COUNT(DISTINCT c.id) AS total_clases,
    SUM(c.duracion_horas) AS horas_totales,
    AVG(n.porcentaje) AS promedio_notas,
    metrics.autonomia_porcentaje,
    metrics.fluidez_porcentaje,
    metrics.resiliencia_porcentaje,
    metrics.racha_dias_consecutivos
FROM estudiantes e
LEFT JOIN clases c ON e.id = c.estudiante_id AND c.estado = 'completada'
LEFT JOIN notas n ON e.id = n.estudiante_id
LEFT JOIN LATERAL (
    SELECT autonomia_porcentaje, fluidez_porcentaje, resiliencia_porcentaje, racha_dias_consecutivos
    FROM metricas_objetivas mo
    WHERE mo.estudiante_id = e.id
    ORDER BY mo.fecha DESC, mo.id DESC
    LIMIT 1
) metrics ON TRUE
GROUP BY e.id, metrics.autonomia_porcentaje, metrics.fluidez_porcentaje, metrics.resiliencia_porcentaje, metrics.racha_dias_consecutivos;

CREATE OR REPLACE VIEW vista_calendario_completo AS
SELECT
    c.id,
    c.fecha,
    c.hora_inicio,
    c.hora_fin,
    c.duracion_horas,
    c.modalidad,
    c.direccion,
    e.nombre || ' ' || e.apellido AS estudiante,
    p.nombre || ' ' || p.apellido AS profesor,
    m.nombre AS materia,
    m.nivel,
    c.estado,
    a.estado AS asistencia
FROM clases c
JOIN estudiantes e ON c.estudiante_id = e.id
JOIN profesores p ON c.profesor_id = p.id
JOIN materias m ON c.materia_id = m.id
LEFT JOIN asistencia a ON c.id = a.clase_id AND e.id = a.estudiante_id;

INSERT INTO storage.buckets (id, name, public)
VALUES ('studybuddy-files', 'studybuddy-files', FALSE)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE estudiantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE profesores ENABLE ROW LEVEL SECURITY;
ALTER TABLE materias ENABLE ROW LEVEL SECURITY;
ALTER TABLE syllabus ENABLE ROW LEVEL SECURITY;
ALTER TABLE clases ENABLE ROW LEVEL SECURITY;
ALTER TABLE asistencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE notas ENABLE ROW LEVEL SECURITY;
ALTER TABLE horas_estudiante ENABLE ROW LEVEL SECURITY;
ALTER TABLE reportes_clase ENABLE ROW LEVEL SECURITY;
ALTER TABLE metacognicion ENABLE ROW LEVEL SECURITY;
ALTER TABLE metricas_objetivas ENABLE ROW LEVEL SECURITY;
ALTER TABLE estilo_cognitivo ENABLE ROW LEVEL SECURITY;
ALTER TABLE objetivos_aprendizaje ENABLE ROW LEVEL SECURITY;
ALTER TABLE mensajes ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE pizarra_paginas ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_files ENABLE ROW LEVEL SECURITY;
